import { test } from 'node:test';
import assert from 'node:assert/strict';
import { AccountStore } from './cloudflare-worker.js';

function setup(n=5,used=0) {
  const data=new Map(), clone=v=>structuredClone(v);
  const storage={async get(k){return clone(data.get(k));},async put(k,v){for(const [key,value] of typeof k==='string'?[[k,v]]:Object.entries(k))data.set(key,clone(value));},async delete(k){for(const key of Array.isArray(k)?k:[k])data.delete(key);},async list({prefix='',limit=Infinity,startAfter=''}){return new Map([...data].filter(([k])=>k.startsWith(prefix)&&k>startAfter).sort(([a],[b])=>a.localeCompare(b)).slice(0,limit));},async transaction(fn){return fn(storage);}};
  const tasks=[];const app=new AccountStore({storage,waitUntil:p=>tasks.push(p)},{CHEAPAI_API_KEY:'mock',PROXY_TOKEN:'test-pepper-never-production'});
  const id='test-account-'+n;
  data.set('u:'+id,{id,email:`test-${n}@mama-helper.local`,revision:0,state:{profile:null,messages:[],medicalCard:[],preferences:{repeat:'never',push:false}}});data.set('ai-quota-v1:'+id,used);
  app.identity=async()=>({u:await storage.get('u:'+id),token:'test'});
  let calls=0;let upstream={choices:[{message:{content:'Можно начать с простой игры с ребёнком.'}}]};
  const previousFetch=globalThis.fetch;
  globalThis.fetch=async (_url,options)=>{calls++;if(upstream instanceof Error)throw upstream;if(typeof upstream==='function')return upstream(options);return Response.json(upstream);};
  return {app,data,id,tasks,storage,calls:()=>calls,upstream:v=>upstream=v,cleanup:()=>globalThis.fetch=previousFetch,async ask(question='Во что поиграть с ребёнком?',messageId=crypto.randomUUID(),emit){const u=await storage.get('u:'+id);return app.handle({action:'chat',question,messageId,revision:u.revision},'','',false,emit);}};
}
async function scenario(fn,n=5,used=0){const s=setup(n,used);try{await fn(s);}finally{s.cleanup();}}

test('accounts 2–5 each allow the 70th but not the 71st answer',async()=>{for(const n of [2,3,4,5])await scenario(async s=>{const b=await(await s.ask()).json();assert.equal(b.quota.remaining,0);await assert.rejects(s.ask(),/70 из 70/);assert.equal(s.calls(),1);},n,69);});
test('account 1 has no test quota',()=>scenario(async s=>{await s.ask();assert.equal(s.calls(),1);},1,70));
test('network failures do not charge or persist partial messages',()=>scenario(async s=>{s.upstream(new Error('offline'));await assert.rejects(s.ask());assert.equal(s.data.get('ai-quota-v1:'+s.id),0);assert.equal(s.data.get('u:'+s.id).state.messages.length,0);}));
test('retry of same message does not call AI twice',()=>scenario(async s=>{await s.ask(undefined,'same');await s.ask(undefined,'same');assert.equal(s.calls(),1);}));
test('clearing history cannot reset quota',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await s.app.handle({action:'save',revision:0,state:{...u.state,messages:[],quota:{used:0}}},'','');await assert.rejects(s.ask(),/70 из 70/);},5,70));
test('parallel requests cannot exceed quota',()=>scenario(async s=>{const results=await Promise.allSettled(['a','b'].map(messageId=>s.app.handle({action:'chat',revision:0,messageId,question:'Во что поиграть с ребёнком?'},'','')));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(s.data.get('ai-quota-v1:'+s.id),70);},5,69));
test('BMW, dose requests and emergencies do not use AI',()=>scenario(async s=>{for(const q of ['Расскажи про BMW','Сколько дать лекарства ребёнку?','Хочу навредить ребёнку'])await s.ask(q);assert.equal(s.calls(),0);}));
test('age gate checks profile before calling AI',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.profile={role:'mom',stage:'child',birthDate:new Date().toISOString().slice(0,10),childName:'Миша'};const b=await(await s.ask('Хочу дать ребёнку борщ')).json();assert.match(b.answer,/слишком рано/);assert.equal(s.calls(),0);}));
test('short follow-up stays in context',()=>scenario(async s=>{await s.ask();await s.ask('А подробнее?');assert.equal(s.calls(),2);}));
test('memory is proposed, not automatically confirmed',()=>scenario(async s=>{const b=await(await s.ask('Сегодня были у педиатра')).json();assert.equal(b.state.medicalCard.length,0);assert.equal(b.state.pendingMemory.length,1);}));
test('questions do not become memories',()=>scenario(async s=>{const b=await(await s.ask('Когда идти к педиатру?')).json();assert.equal(b.state.pendingMemory.length,0);}));
test('fake sources and dosage output fail without charge',()=>scenario(async s=>{for(const text of ['Я проверил в интернете https://example.com','Давайте 10 мг препарата']){s.upstream({choices:[{message:{content:text}}]});await assert.rejects(s.ask());assert.equal(s.data.get('ai-quota-v1:'+s.id),0);}}));
test('feedback defaults to no profile, messages or answer',()=>scenario(async s=>{const b=await(await s.ask()).json();await s.app.handle({action:'feedback',kind:'unsafe',messageId:b.state.messages.at(-1).id},'','');const report=[...s.data.values()].find(v=>v.kind==='unsafe');assert.equal(report.profile,undefined);assert.equal(report.messages,undefined);assert.equal(report.answer,undefined);}));
test('feedback includes context only with explicit consent',()=>scenario(async s=>{const b=await(await s.ask()).json();await s.app.handle({action:'feedback',kind:'helpful',messageId:b.state.messages.at(-1).id,consentContext:true},'','');const report=[...s.data.values()].find(v=>v.kind==='helpful');assert.equal(report.messages.length,2);}));
test('administrative export and invitation require service secret',()=>scenario(async s=>{for(const action of ['feedback-export','invite-create'])await assert.rejects(s.app.handle({action},'',''),/организатору/);}));
test('stream emits text and commits exactly once',()=>scenario(async s=>{s.upstream(()=>new Response('data: '+JSON.stringify({choices:[{delta:{content:'Простая игра.\n'}}]})+'\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}}));const events=[];await s.ask(undefined,undefined,async e=>events.push(e));assert.equal(events[0].text,'Простая игра.\n');assert.equal(s.data.get('ai-quota-v1:'+s.id),1);}));
test('truncated upstream stream is not charged',()=>scenario(async s=>{s.upstream(()=>new Response('data: '+JSON.stringify({choices:[{delta:{content:'Часть ответа'}}]})+'\n\n',{headers:{'Content-Type':'text/event-stream'}}));await assert.rejects(s.ask(undefined,undefined,async()=>{}),/прервалась/);assert.equal(s.data.get('ai-quota-v1:'+s.id),0);}));
test('stream transport returns final state with NDJSON',()=>scenario(async s=>{const r=await s.app.fetch(new Request('https://internal/action',{method:'POST',body:JSON.stringify({action:'chat',stream:true,question:'Во что поиграть с ребёнком?',messageId:'stream',revision:0})}));const events=(await r.text()).trim().split('\n').map(JSON.parse);assert.equal(events.at(-1).type,'result');assert.equal(events.at(-1).data.quota.remaining,69);await Promise.all(s.tasks);}));
test('test account 5 login works with password 5',()=>scenario(async s=>{const r=await s.app.handle({action:'login',email:'5',password:'5'},'','');const b=await r.json();assert.equal(b.user.id,'test-account-5');assert.ok(b.sessionToken);}));
test('invitation is single-use, validation failure does not consume it',()=>scenario(async s=>{const r=await s.app.handle({action:'invite-create'},'','Bearer test-pepper-never-production');const {url}=await r.json();const invite=new URLSearchParams(new URL(url).hash.slice(1)).get('invite');await assert.rejects(s.app.handle({action:'register',invite,email:'bad',password:'short',consent:true},'',''));const b=await(await s.app.handle({action:'register',invite,email:'one@example.com',password:'a-long-test-password',consent:true},'','')).json();assert.ok(b.recoveryCode);await assert.rejects(s.app.handle({action:'register',invite,email:'two@example.com',password:'a-long-test-password',consent:true},'',''),/использовано/);}));
test('only active conversation and confirmed card enter context',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.conversations=[{id:'old',title:'Old',messages:[{id:'archived',role:'user',text:'ARCHIVED_PRIVATE_SENTINEL'}]}];u.state.pendingMemory=[{id:'pending',date:'2026-01-01',text:'PENDING_SENTINEL',source:'chat'}];s.upstream(options=>{const body=JSON.parse(options.body);assert.ok(!JSON.stringify(body).includes('ARCHIVED_PRIVATE_SENTINEL'));assert.ok(!JSON.stringify(body).includes('PENDING_SENTINEL'));return Response.json({choices:[{message:{content:'Можно обсудить игру.'}}]});});await s.ask();}));
const birthMonthsAgo=months=>{const now=new Date();return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-months,1)).toISOString().slice(0,10);};
test('preschool topics reach AI with age and school safeguards',async()=>{for(const months of [36,48,60,72,83])await scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.profile={stage:'child',role:'dad',birthDate:birthMonthsAgo(months),childName:'Тестовый ребёнок'};s.upstream(options=>{const b=JSON.parse(options.body),context=JSON.stringify(b.messages);assert.match(context,new RegExp(months+' полных месяцев'));assert.match(context,/Не требуй чтения до школы/);assert.match(context,/не выноси|не ставь оценку/);return Response.json({choices:[{message:{content:'Давайте выберем совместную игру.'}}]});});await s.ask('Как готовиться к школе?');assert.equal(s.calls(),1);});});
test('seventh birthday stops personalised child advice without charge',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'child',role:'mom',birthDate:birthMonthsAgo(84)};const b=await(await s.ask('Как готовиться к школе?')).json();assert.match(b.answer,/7 лет/);assert.equal(s.calls(),0);assert.equal(s.data.get('ai-quota-v1:'+s.id),0);}));
test('preschool scope preserves emergency priority',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'child',role:'mom',birthDate:birthMonthsAgo(72)};const b=await(await s.ask('Перед школой ребёнок задыхается')).json();assert.match(b.answer,/112/);assert.equal(s.calls(),0);}));
test('new birthdays support six-year-olds but reject seven-year-olds',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await s.app.handle({action:'save',revision:0,state:{...u.state,profile:{stage:'child',role:'mom',childName:'Саша',birthDate:birthMonthsAgo(83)}}},'','');await assert.rejects(s.app.handle({action:'save',revision:1,state:{...u.state,profile:{stage:'child',role:'mom',childName:'Саша',birthDate:birthMonthsAgo(84)}}},'',''),/младше 7/);}));
test('completed preschool activity is accepted and proposed for memory',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'child',role:'mom',birthDate:birthMonthsAgo(60),childName:'Саша'};const b=await(await s.ask('Сегодня мы с Сашей читали книгу и считали предметы')).json();assert.equal(s.calls(),1);assert.equal(b.state.pendingMemory.length,1);assert.match(b.state.pendingMemory[0].text,/читали книгу/);}));
test('child profile requires a name while pregnancy may omit it',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await assert.rejects(s.app.handle({action:'save',revision:0,state:{...u.state,profile:{stage:'child',role:'mom',birthDate:birthMonthsAgo(12)}}},'',''),/имя ребёнка/);const r=await s.app.handle({action:'save',revision:0,state:{...u.state,profile:{stage:'pregnancy',role:'mom',week:20,weekDate:new Date().toISOString().slice(0,10)}}},'','');assert.equal(r.status,200);}));
