import { test } from 'node:test';
import assert from 'node:assert/strict';
import { AccountStore } from './cloudflare-worker.js';
import {emptyCare} from './services.js';

function setup(n=5,used=0) {
  const data=new Map(), clone=v=>structuredClone(v);
  const storage={async get(k){return clone(data.get(k));},async put(k,v){for(const [key,value] of typeof k==='string'?[[k,v]]:Object.entries(k))data.set(key,clone(value));},async delete(k){for(const key of Array.isArray(k)?k:[k])data.delete(key);},async list({prefix='',limit=Infinity,startAfter=''}){return new Map([...data].filter(([k])=>k.startsWith(prefix)&&k>startAfter).sort(([a],[b])=>a.localeCompare(b)).slice(0,limit));},async transaction(fn){return fn(storage);}};
  const tasks=[];const app=new AccountStore({storage,waitUntil:p=>tasks.push(p)},{CHEAPAI_API_KEY:'mock',PROXY_TOKEN:'test-pepper-never-production'});
  const id='test-account-'+n;
  data.set('u:'+id,{id,email:`test-${n}@mama-helper.local`,revision:0,state:{profile:{role:'mom',stage:'child',birthDate:'2024-09-17',childName:'Миша'},messages:[],medicalCard:[],preferences:{repeat:'never',push:false}}});data.set('ai-quota-v1:'+id,used);
  app.identity=async()=>({u:await storage.get('u:'+id),token:'test'});
  let calls=0;let upstream={choices:[{message:{content:'Можно начать с простой игры с ребёнком.'}}]};
  const previousFetch=globalThis.fetch;
  globalThis.fetch=async (_url,options)=>{calls++;if(upstream instanceof Error)throw upstream;if(typeof upstream==='function')return upstream(options);return Response.json(upstream);};
  return {app,data,id,tasks,storage,calls:()=>calls,upstream:v=>upstream=v,cleanup:()=>globalThis.fetch=previousFetch,async ask(question='Во что поиграть с ребёнком?',messageId=crypto.randomUUID(),emit){const u=await storage.get('u:'+id);return app.handle({action:'chat',question,messageId,revision:u.revision},'','',false,emit);}};
}
async function scenario(fn,n=5,used=0){const s=setup(n,used);try{await fn(s);}finally{s.cleanup();}}

test('care data stays local and is not sent to AI',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);const care={...emptyCare(),tasks:[{id:'task',title:'Наша игра',detail:'Смотрели книгу',date:'2026-09-17',status:'done',result:'hard',feedback:'CARE_RESULT_SENTINEL'}]};await s.app.handle({action:'save',revision:0,state:{...u.state,care}},'','');s.upstream(options=>{assert.doesNotMatch(options.body,/CARE_RESULT_SENTINEL|Наша игра/);return Response.json({choices:[{message:{content:'Предложим более простую игру.'}}]});});await s.ask('Адаптируй игру для ребёнка');assert.equal(s.data.get('u:'+s.id).state.care.tasks.length,1);}));
test('invalid diary is rejected before any write',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await assert.rejects(s.app.handle({action:'save',revision:0,state:{...u.state,care:{diary:[{minutes:-5}]}}},'',''),/дневник/);assert.equal(s.data.get('u:'+s.id).revision,0);}));
test('answer passport does not claim independent validation',()=>scenario(async s=>{const b=await(await s.ask()).json();const e=b.state.messages.at(-1).evidence;assert.equal(e.sources.length,0);assert.match(e.limitation,/может содержать ошибки/);}));

test('accounts 2–6 each allow the 70th but not the 71st answer',async()=>{for(const n of [2,3,4,5,6])await scenario(async s=>{const b=await(await s.ask()).json();assert.equal(b.quota.remaining,0);await assert.rejects(s.ask(),/70 из 70/);assert.equal(s.calls(),1);},n,69);});
test('account 1 has no test quota',()=>scenario(async s=>{await s.ask();assert.equal(s.calls(),1);},1,70));
test('network failures do not charge or persist partial messages',()=>scenario(async s=>{s.upstream(new Error('offline'));await assert.rejects(s.ask());assert.equal(s.data.get('ai-quota-v1:'+s.id),0);assert.equal(s.data.get('u:'+s.id).state.messages.length,0);}));
test('retry of same message does not call AI twice',()=>scenario(async s=>{await s.ask(undefined,'same');await s.ask(undefined,'same');assert.equal(s.calls(),1);}));
test('clearing history cannot reset quota',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await s.app.handle({action:'save',revision:0,state:{...u.state,messages:[],quota:{used:0}}},'','');await assert.rejects(s.ask(),/70 из 70/);},5,70));
test('parallel requests cannot exceed quota',()=>scenario(async s=>{const results=await Promise.allSettled(['a','b'].map(messageId=>s.app.handle({action:'chat',revision:0,messageId,question:'Во что поиграть с ребёнком?'},'','')));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(s.data.get('ai-quota-v1:'+s.id),70);},5,69));
test('BMW, dose requests and emergencies do not use AI',()=>scenario(async s=>{for(const q of ['Расскажи про BMW','Сколько дать лекарства ребёнку?','Хочу навредить ребёнку'])await s.ask(q);assert.equal(s.calls(),0);}));
test('out-of-scope reply does not name unrelated examples',()=>scenario(async s=>{const b=await(await s.ask('Расскажи про BMW')).json();assert.doesNotMatch(b.answer,/BMW|автомоб|программирован/i);}));
test('kindergarten packing is treated as parent help',()=>scenario(async s=>{await s.ask('Как собрать ребёнка в сад?');assert.equal(s.calls(),1);}));
test('food and drawing phrasing stay in parenting scope',async()=>{for(const q of ['Не хочет пробовать новую еду. Как предлагать без давления?','Как поддержать интерес к рисованию без требований сделать красиво?'])await scenario(async s=>{await s.ask(q);assert.equal(s.calls(),1);});});
test('one dialogue can retain fifty question and answer pairs',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);const messages=Array.from({length:100},(_,index)=>({id:`message-${index}`,role:index%2?'assistant':'user',text:index%2?'Ответ родителю.':'Вопрос родителя?'}));const response=await s.app.handle({action:'save',revision:0,state:{...u.state,messages}},'','');assert.equal(response.status,200);assert.equal(s.data.get('u:'+s.id).state.messages.length,100);}));
test('age answer follows the assistant clarification instead of becoming off-topic',()=>scenario(async s=>{s.upstream({choices:[{message:{content:'Сколько лет ребёнку?'}}]});await s.ask('Сделай план развивающих игр на день');s.upstream({choices:[{message:{content:'Вот гибкий план игр на день.'}}]});const b=await(await s.ask('2 года')).json();assert.equal(s.calls(),2);assert.doesNotMatch(b.answer,/Этот помощник отвечает/);}));
test('profile is required before personalised advice reaches AI',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile=null;const b=await(await s.ask('Сделай план развивающих игр на день')).json();assert.match(b.answer,/заполните профиль/i);assert.equal(s.calls(),0);}));
test('age gate checks profile before calling AI',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.profile={role:'mom',stage:'child',birthDate:new Date().toISOString().slice(0,10),childName:'Миша'};const b=await(await s.ask('Хочу дать ребёнку борщ')).json();assert.match(b.answer,/слишком рано/);assert.equal(s.calls(),0);}));
test('short follow-up stays in context',()=>scenario(async s=>{await s.ask();await s.ask('А подробнее?');assert.equal(s.calls(),2);}));
test('memory is proposed, not automatically confirmed',()=>scenario(async s=>{const b=await(await s.ask('Сегодня были у педиатра')).json();assert.equal(b.state.medicalCard.length,0);assert.equal(b.state.pendingMemory.length,1);}));
test('questions do not become memories',()=>scenario(async s=>{const b=await(await s.ask('Когда идти к педиатру?')).json();assert.equal(b.state.pendingMemory.length,0);}));
test('fake sources and dosage output fail without charge',()=>scenario(async s=>{for(const text of ['Я проверил в интернете https://example.com','Давайте 10 мг препарата']){s.upstream({choices:[{message:{content:text}}]});await assert.rejects(s.ask());assert.equal(s.data.get('ai-quota-v1:'+s.id),0);}}));
test('feedback defaults to no profile, messages or answer',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile=null;const b=await(await s.ask()).json();await s.app.handle({action:'feedback',kind:'unsafe',messageId:b.state.messages.at(-1).id},'','');const report=[...s.data.values()].find(v=>v.kind==='unsafe');assert.equal(report.profile,undefined);assert.equal(report.messages,undefined);assert.equal(report.answer,undefined);}));
test('feedback includes context only with explicit consent',()=>scenario(async s=>{const b=await(await s.ask()).json();await s.app.handle({action:'feedback',kind:'helpful',messageId:b.state.messages.at(-1).id,consentContext:true},'','');const report=[...s.data.values()].find(v=>v.kind==='helpful');assert.equal(report.messages.length,2);}));
test('administrative export and invitation require service secret',()=>scenario(async s=>{for(const action of ['feedback-export','invite-create'])await assert.rejects(s.app.handle({action},'',''),/организатору/);}));
test('stream emits text and commits exactly once',()=>scenario(async s=>{s.upstream(()=>new Response('data: '+JSON.stringify({choices:[{delta:{content:'Простая игра.\n'}}]})+'\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}}));const events=[];await s.ask(undefined,undefined,async e=>events.push(e));assert.equal(events[0].text,'Простая игра.\n');assert.equal(s.data.get('ai-quota-v1:'+s.id),1);}));
test('truncated upstream stream is not charged',()=>scenario(async s=>{s.upstream(()=>new Response('data: '+JSON.stringify({choices:[{delta:{content:'Часть ответа'}}]})+'\n\n',{headers:{'Content-Type':'text/event-stream'}}));await assert.rejects(s.ask(undefined,undefined,async()=>{}),/прервалась/);assert.equal(s.data.get('ai-quota-v1:'+s.id),0);}));
test('stream transport returns final state with NDJSON',()=>scenario(async s=>{const r=await s.app.fetch(new Request('https://internal/action',{method:'POST',body:JSON.stringify({action:'chat',stream:true,question:'Во что поиграть с ребёнком?',messageId:'stream',revision:0})}));const events=(await r.text()).trim().split('\n').map(JSON.parse);assert.equal(events.at(-1).type,'result');assert.equal(events.at(-1).data.quota.remaining,69);await Promise.all(s.tasks);}));
test('test account 5 login works with password 5',()=>scenario(async s=>{const r=await s.app.handle({action:'login',email:'5',password:'5'},'','');const b=await r.json();assert.equal(b.user.id,'test-account-5');assert.ok(b.sessionToken);}));
test('test account 6 login works with password 6',()=>scenario(async s=>{const r=await s.app.handle({action:'login',email:'6',password:'6'},'','');const b=await r.json();assert.equal(b.user.id,'test-account-6');assert.ok(b.sessionToken);}));
test('invitation is single-use, validation failure does not consume it',()=>scenario(async s=>{const r=await s.app.handle({action:'invite-create'},'','Bearer test-pepper-never-production');const {url}=await r.json();const invite=new URLSearchParams(new URL(url).hash.slice(1)).get('invite');await assert.rejects(s.app.handle({action:'register',invite,email:'bad',password:'short',consent:true},'',''));const b=await(await s.app.handle({action:'register',invite,email:'one@example.com',password:'a-long-test-password',consent:true},'','')).json();assert.ok(b.recoveryCode);await assert.rejects(s.app.handle({action:'register',invite,email:'two@example.com',password:'a-long-test-password',consent:true},'',''),/использовано/);}));
test('only active conversation and confirmed card enter context',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.conversations=[{id:'old',title:'Old',messages:[{id:'archived',role:'user',text:'ARCHIVED_PRIVATE_SENTINEL'}]}];u.state.pendingMemory=[{id:'pending',date:'2026-01-01',text:'PENDING_SENTINEL',source:'chat'}];s.upstream(options=>{const body=JSON.parse(options.body);assert.ok(!JSON.stringify(body).includes('ARCHIVED_PRIVATE_SENTINEL'));assert.ok(!JSON.stringify(body).includes('PENDING_SENTINEL'));return Response.json({choices:[{message:{content:'Можно обсудить игру.'}}]});});await s.ask();}));
test('chat history stays local and is not sent to AI',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.messages=[{id:'old-u',role:'user',text:'МИШКА_PRIVATE_SENTINEL'},{id:'old-a',role:'assistant',text:'Ответ PRIVATE_SENTINEL'}];s.upstream(options=>{assert.doesNotMatch(options.body,/PRIVATE_SENTINEL|old-u|old-a/);return Response.json({choices:[{message:{content:'Продолжите игру.'}}]});});await s.ask('Как продолжить игру?');assert.equal(s.calls(),1);}));
test('AI receives only question and derived age, never identity fields',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.profile={stage:'child',role:'mom',birthDate:'2024-09-17',childName:'ИМЯ_PRIVATE',feeding:'breast',sleep:'SLEEP_PRIVATE',health:'HEALTH_PRIVATE',healthConfirmed:true};s.upstream(options=>{const body=JSON.stringify(JSON.parse(options.body));assert.match(body,/Во что играть/);assert.match(body,/возраст: 2 лет, 0 месяцев/);assert.doesNotMatch(body,/ИМЯ_PRIVATE|2024-09-17|SLEEP_PRIVATE|HEALTH_PRIVATE|breast|test-account-5|mama-helper\.local/);return Response.json({choices:[{message:{content:'Можно выбрать простую игру.'}}]});});await s.ask('Во что играть?');}));
const birthMonthsAgo=months=>{const now=new Date();return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-months,1)).toISOString().slice(0,10);};
test('pregnancy rejects child activities and explicit ages without AI or quota',async()=>{for(const q of ['Как играть с ребенком в 2 года?','Во что играть с двухлетним ребенком?','Посоветуй развивающие игры','На будущее составь занятия для ребенка трех лет','Что приготовить ребенку в два года?'])await scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.profile={stage:'pregnancy',role:'mom',week:20,weekDate:new Date().toISOString().slice(0,10)};const events=[];const b=await(await s.ask(q,undefined,async e=>events.push(e))).json();assert.match(b.answer,/профиле указана беременность/);assert.equal(s.calls(),0);assert.equal(s.data.get('ai-quota-v1:'+s.id),0);assert.equal(b.state.pendingMemory.length,0);assert.equal(events.length,0);});});
test('pregnancy context has strict scope and no preschool instructions',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'pregnancy',role:'mom',week:20,weekDate:new Date().toISOString().slice(0,10)};s.upstream(options=>{const messages=JSON.parse(options.body).messages;const system=messages.filter(m=>m.role==='system').map(m=>m.content).join('\n');assert.match(system,/ОБЯЗАТЕЛЬНАЯ ОБЛАСТЬ ПРОФИЛЯ: беременность/);assert.doesNotMatch(system,/Для 3–4 лет предлагай/);return Response.json({choices:[{message:{content:'Можно составить список вещей для роддома.'}}]});});await s.ask('Как подготовиться к родам?');assert.equal(s.calls(),1);}));
test('child profile refuses another age and another child',async()=>{for(const q of ['Во что играть с ребенком в 5 лет?','Посоветуй игры для другого ребенка','Как уложить ребенка подруги?'])await scenario(async s=>{s.data.get('u:'+s.id).state.profile.birthDate=birthMonthsAgo(24);const b=await(await s.ask(q)).json();assert.match(b.answer,/текущему профилю/);assert.equal(s.calls(),0);});});
test('matching age still reaches AI',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile.birthDate=birthMonthsAgo(24);await s.ask('Во что играть с ребенком в 2 года?');assert.equal(s.calls(),1);}));
test('pregnancy restriction preserves emergency priority',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'pregnancy',role:'mom',week:20,weekDate:new Date().toISOString().slice(0,10)};const b=await(await s.ask('Ребенок 2 года задыхается')).json();assert.match(b.answer,/112/);assert.equal(s.calls(),0);}));
test('preschool safeguards use derived age without profile details',async()=>{for(const months of [36,48,60,72,83])await scenario(async s=>{const u=s.data.get('u:'+s.id);u.state.profile={stage:'child',role:'dad',birthDate:birthMonthsAgo(months),childName:'Тестовый ребёнок'};s.upstream(options=>{const b=JSON.parse(options.body),context=JSON.stringify(b.messages);assert.match(context,/полных месяцев/);assert.match(context,/Не требуй чтения до школы/);assert.match(context,/не выноси|не ставь оценку/);assert.doesNotMatch(context,/Тестовый ребёнок/);return Response.json({choices:[{message:{content:'Давайте выберем совместную игру.'}}]});});await s.ask('Как готовиться к школе?');assert.equal(s.calls(),1);});});
test('seventh birthday stops personalised child advice without charge',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'child',role:'mom',birthDate:birthMonthsAgo(84)};const b=await(await s.ask('Как готовиться к школе?')).json();assert.match(b.answer,/7 лет/);assert.equal(s.calls(),0);assert.equal(s.data.get('ai-quota-v1:'+s.id),0);}));
test('preschool scope preserves emergency priority',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'child',role:'mom',birthDate:birthMonthsAgo(72)};const b=await(await s.ask('Перед школой ребёнок задыхается')).json();assert.match(b.answer,/112/);assert.equal(s.calls(),0);}));
test('new birthdays support six-year-olds but reject seven-year-olds',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await s.app.handle({action:'save',revision:0,state:{...u.state,profile:{stage:'child',role:'mom',childName:'Саша',birthDate:birthMonthsAgo(83)}}},'','');await assert.rejects(s.app.handle({action:'save',revision:1,state:{...u.state,profile:{stage:'child',role:'mom',childName:'Саша',birthDate:birthMonthsAgo(84)}}},'',''),/младше 7/);}));
test('completed preschool activity is accepted and proposed for memory',()=>scenario(async s=>{s.data.get('u:'+s.id).state.profile={stage:'child',role:'mom',birthDate:birthMonthsAgo(60),childName:'Саша'};const b=await(await s.ask('Сегодня мы с Сашей читали книгу и считали предметы')).json();assert.equal(s.calls(),1);assert.equal(b.state.pendingMemory.length,1);assert.match(b.state.pendingMemory[0].text,/читали книгу/);}));
test('child profile requires a name while pregnancy may omit it',()=>scenario(async s=>{const u=s.data.get('u:'+s.id);await assert.rejects(s.app.handle({action:'save',revision:0,state:{...u.state,profile:{stage:'child',role:'mom',birthDate:birthMonthsAgo(12)}}},'',''),/имя ребёнка/);const r=await s.app.handle({action:'save',revision:0,state:{...u.state,profile:{stage:'pregnancy',role:'mom',week:20,weekDate:new Date().toISOString().slice(0,10)}}},'','');assert.equal(r.status,200);}));
