import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyCare,validateCare,dayIdeas,makeDayPlan,makeWeek,monthsOld,diarySummary,safetyItems,addDays,careContext} from './services.js';
const date='2026-09-17';
const profile=months=>({stage:'child',birthDate:new Date(Date.UTC(2026,8-months,1)).toISOString().slice(0,10),childName:'Тест',role:'mom'});
test('empty care migrates existing accounts without losing compatibility',()=>assert.deepEqual(validateCare(),emptyCare()));
test('malformed care is rejected',()=>{for(const x of [null,[],{tasks:'bad'},{followups:'true'},{diary:[{}]},{achievements:[{}]},{appointments:[{}]}])assert.throws(()=>validateCare(x));});
test('only supported top-level care fields survive',()=>assert.equal(validateCare({...emptyCare(),secret:'x'}).secret,undefined));
test('one child profile required for activities',()=>assert.deepEqual(makeWeek(null),[]));
test('all age groups have five activities with deterministic identifiers',()=>{for(const m of [0,3,6,12,24,36,48,60,72,83]){const p=profile(m);const a=makeWeek(p,emptyCare(),date);assert.equal(a.length,5);assert.equal(new Set(a.map(x=>x.id)).size,5);assert.deepEqual(a,makeWeek(p,emptyCare(),date));validateCare({...emptyCare(),tasks:a});}});
test('pregnancy plan has no child exercises',()=>{const tasks=makeWeek({stage:'pregnancy'},emptyCare(),date);assert.equal(tasks.length,5);assert.match(tasks[0].detail,/./);assert.ok(tasks.every(t=>!t.title.includes('История')));});
test('my day offers four ideas and creates three tasks for today',()=>{const p=profile(36),ideas=dayIdeas(p,emptyCare(),date),tasks=makeDayPlan(p,emptyCare(),date);assert.equal(ideas.length,4);assert.equal(tasks.length,3);assert.ok(tasks.every(t=>t.date===date&&t.id.startsWith('day-')));});
test('school vocabulary activities do not go to infants',()=>assert.ok(makeWeek(profile(3),emptyCare(),date).every(t=>!['words','turns','story'].includes(t.template))));
test('age limit respected',()=>assert.deepEqual(makeWeek(profile(85),emptyCare(),date),[]));
test('end-of-month birthdays calculate correctly',()=>assert.equal(monthsOld({stage:'child',birthDate:'2024-01-31'},new Date('2024-02-29T12:00:00Z')),1));
test('calendar moves over leap day',()=>assert.equal(addDays('2024-02-28',2),'2024-03-01'));
test('hard activities are skipped for fourteen days',()=>{const c=emptyCare();c.tasks=[{id:'x',template:'book',date,result:'hard'}];assert.ok(makeWeek(profile(24),c,date).every(t=>t.template!=='book'));});
test('future and older diary records excluded, multiple moods count once per day',()=>{const c=emptyCare();c.diary=[{date,kind:'sleep',minutes:30},{date,kind:'sleep',minutes:20},{date,kind:'mood',mood:'hard'},{date,kind:'mood',mood:'hard'},{date:'2026-09-01',kind:'sleep',minutes:1000},{date:'2026-09-18',kind:'sleep',minutes:50}];assert.equal(diarySummary(c,date).sleepMinutes,50);assert.equal(diarySummary(c,date).difficultDays,1);});
test('safety items appear only from parent-reported movement',()=>{const c=emptyCare();assert.equal(safetyItems(c).length,2);c.achievements=[{kind:'roll'},{kind:'crawl'},{kind:'stand'}];assert.equal(safetyItems(c).length,6);});
test('dates and duplicates rejected',()=>{const c=emptyCare();const task={id:'x',title:'test',detail:'test',date:'2026-02-31',status:'planned',feedback:''};assert.throws(()=>validateCare({...c,tasks:[task]}));task.date=date;assert.throws(()=>validateCare({...c,tasks:[task,task]}));});
test('sleep duration bounded',()=>{for(const minutes of [-1,1441,Infinity])assert.throws(()=>validateCare({...emptyCare(),diary:[{id:'x',date,kind:'sleep',note:'',minutes}]}));});
test('care context bounded to most recent records',()=>{const c=emptyCare();c.diary=Array.from({length:100},(_,i)=>({note:'note-'+i}));const ctx=JSON.parse(careContext(c));assert.equal(ctx.diary.length,20);assert.equal(ctx.diary[0].note,'note-80');});
