import {useEffect,useRef,useState} from 'react';
import {CalendarDays,Heart,Mic,MicOff,Volume2,Square,Sparkles,ArrowLeft,Check,Plus,ClipboardList,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {contextLabel,Message,ParentState} from '@/lib/parent-model';
import {addDays,CareTask,CareState,DiaryEntry,Achievement,Appointment,dayIdeas,diarySummary,emptyCare,localDay,makeDayPlan,makeWeek,monthsOld,safetyItems,serviceCatalog} from '../../ai-proxy/services';
import './parent-services.css';

type Props={state:ParentState;busy:boolean;save:(state:ParentState,notice?:string)=>Promise<boolean>;ask:(q:string)=>void;onProfile:()=>void};
const labels:Record<string,string>={sleep:'Сон',feeding:'Кормление',mood:'Самочувствие родителя',note:'Наблюдение'};
const eventLabels:Record<string,string>={roll:'Переворачивается',crawl:'Ползает',stand:'Встаёт у опоры',walk:'Ходит',custom:'Наше маленькое открытие'};
const uid=()=>crypto.randomUUID();
function download(name:string,text:string,type='text/plain;charset=utf-8'){
 const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function calendarDownload(task:CareTask){
 // Date-only neutral entry: no child's name or health data leaks into lock-screen text.
 const day=task.reviewDate||task.date;
 const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MamaHelper//Care//RU','BEGIN:VEVENT',`UID:${task.id.replace(/[^\w-]/g,'')}@mama-helper`,`DTSTAMP:${new Date().toISOString().replace(/[-:]|\.\d{3}/g,'')}`,`DTSTART;VALUE=DATE:${day.replace(/-/g,'')}`,`DTEND;VALUE=DATE:${addDays(day,1).replace(/-/g,'')}`,'SUMMARY:Открыть личный план заботы','DESCRIPTION:Посмотрите ваши задачи в личном кабинете.','END:VEVENT','END:VCALENDAR'].join('\r\n');
 download('care-reminder.ics',content,'text/calendar;charset=utf-8');
}

export function SaveAction({message,state,save,busy}:{message:Message}&Pick<Props,'state'|'save'|'busy'>){
 const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[detail,setDetail]=useState(''),[date,setDate]=useState(localDay()),[review,setReview]=useState(addDays(localDay(),3));
 return <><Button variant="outline" disabled={busy} className="mt-3" onClick={()=>{setDetail(message.text);setTitle('Мой следующий шаг');setOpen(true);}}><Plus size={16}/>В мой план</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="service-dialog"><DialogHeader><DialogTitle>Один следующий шаг</DialogTitle><DialogDescription>Выберите выполнимое действие из ответа. Это личная запись, не медицинское назначение.</DialogDescription></DialogHeader><form className="service-stack" onSubmit={async e=>{e.preventDefault();const care=state.care||emptyCare();if(await save({...state,care:{...care,tasks:[...care.tasks,{id:uid(),title:title.trim(),detail:detail.trim(),date,status:'planned',reviewDate:review||undefined,feedback:''}]}},'Действие сохранено'))setOpen(false);}}><label className="form-field">Название<Input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="form-field">Что попробую<Textarea required maxLength={2500} value={detail} onChange={e=>setDetail(e.target.value)}/></label><label className="form-field">Когда<Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="form-field">Когда спросить о результате · необязательно<Input type="date" min={date} value={review} onChange={e=>setReview(e.target.value)}/></label><p className="muted text-sm">Вопрос появится в «Моём дне», когда вы откроете кабинет. Фоновый push не отправляется.</p><Button disabled={busy||!title.trim()||!detail.trim()}>Сохранить</Button></form></DialogContent></Dialog></>;
}
export function EvidencePassport({message}:{message:Message}){
 const e=message.evidence;
 return <details className="evidence-passport"><summary><ShieldCheck size={16}/>О характере ответа</summary><p>{e?.basis||'Знания AI и контекст текущего разговора'}</p><p>Ответ может содержать ошибки. Важные решения лучше перепроверять у подходящего специалиста.</p></details>;
}

type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:{results:{[key:number]:{[key:number]:{transcript:string}}}})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type VoiceWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export function VoiceInput({onText,disabled}:{onText:(text:string)=>void;disabled:boolean}){
 const [open,setOpen]=useState(false),[listening,setListening]=useState(false),[error,setError]=useState('');const recognition=useRef<Recognition>();
 const Constructor=(window as VoiceWindow).SpeechRecognition||(window as VoiceWindow).webkitSpeechRecognition;
 useEffect(()=>()=>{recognition.current?.abort();},[]);
 useEffect(()=>{if(disabled)recognition.current?.abort();},[disabled]);
 function start(){setError('');setOpen(false);if(!Constructor)return;const r=new Constructor();recognition.current=r;r.lang='ru-RU';r.continuous=false;r.interimResults=false;r.onresult=e=>onText(e.results[0][0].transcript);r.onerror=()=>{setError('Не удалось распознать речь. Используйте диктовку клавиатуры или текст.');setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setError('Микрофон недоступен.');}}
 return <div className="voice-row"><Button type="button" size="icon" variant="outline" title={listening?'Остановить запись':'Голосовой ввод'} aria-label={listening?'Остановить запись':'Голосовой ввод'} disabled={disabled||!Constructor} onClick={()=>listening?recognition.current?.stop():setOpen(true)}>{listening?<MicOff size={18}/>:<Mic size={18}/>}</Button>{!Constructor&&<small>Можно использовать микрофон клавиатуры телефона.</small>}{error&&<p role="alert">{error}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Включить микрофон?</DialogTitle><DialogDescription>Распознавание выполняет браузер: звук может отправляться его провайдеру. Наш сайт не сохраняет аудиозапись. Текст сначала появится в поле ввода — проверьте его перед отправкой AI. Не произносите личные документы.</DialogDescription></DialogHeader><Button onClick={start}>Разрешить и начать</Button><Button variant="outline" onClick={()=>setOpen(false)}>Отмена</Button></DialogContent></Dialog></div>;
}
export function ReadAnswer({text}:{text:string}){
 const [speaking,setSpeaking]=useState(false);
 useEffect(()=>()=>{window.speechSynthesis?.cancel();},[]);
 if(!('speechSynthesis' in window))return null;
 return <Button type="button" variant="ghost" onClick={()=>{speechSynthesis.cancel();if(speaking){setSpeaking(false);return;}const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';const local=speechSynthesis.getVoices().find(v=>v.localService&&v.lang.startsWith('ru'));if(!local){window.alert('Локальный русский голос не установлен. Для приватности используйте системное чтение экрана.');return;}u.voice=local;u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);setSpeaking(true);speechSynthesis.speak(u);}}>{speaking?<Square size={16}/>:<Volume2 size={16}/>} {speaking?'Остановить':'Прослушать'}</Button>;
}

export default function ParentServices({state,busy,save,ask,onProfile}:Props){
 const care=state.care||emptyCare(),p=state.profile,day=localDay(),age=monthsOld(p),summary=diarySummary(care);
 const [panel,setPanel]=useState('overview'),[service,setService]=useState(''),[context,setContext]=useState(''),[minutes,setMinutes]=useState('5');
 const [entry,setEntry]=useState<DiaryEntry>({id:uid(),date:day,kind:'note',note:'',mood:''});
 const [achievement,setAchievement]=useState<Achievement>({id:uid(),date:day,kind:'custom',note:''});
 const [appointment,setAppointment]=useState<Appointment>({id:uid(),date:day,reason:'',questions:'',instructions:''});
 const [feedback,setFeedback]=useState<Record<string,string>>({});
 const [newTask,setNewTask]=useState('');
 const update=(next:CareState,notice='Сохранено')=>save({...state,care:next},notice);
 const tasks=care.tasks.filter(t=>t.date<=day&&t.status==='planned');
 const ideas=dayIdeas(p,care,day);
 const reviews=care.followups?care.tasks.filter(t=>t.reviewDate&&t.reviewDate<=day&&!t.result&&t.status!=='skip'):[];
 function openService(id:string){setService(id);setContext('');setPanel('service');}
 function serviceQuestion(){
  const instructions:Record<string,string>={now:'Нужен короткий план на ближайшие минуты. Сначала оцени по описанию признаки срочности, не задерживай обращение за помощью.',play:'Придумай одну игру для моего ребёнка из доступных вещей. Дай цель без обещаний результата, материалы, шаги, упрощение и меры безопасности.',behavior:'Помоги понять поведение моего ребёнка: возможные объяснения без диагноза, мои действия и конкретные спокойные фразы.',dad:'Я папа. Помоги выбрать конкретное дело, которое я возьму на себя, и занятие с ребёнком. Не считай родительские обязанности обязанностями только мамы.',calm:'Мне нужна психологическая поддержка как родителю. Дай бережную короткую практику без задержек дыхания и один следующий шаг. Это не замена терапии.',kindergarten:'Помоги подготовить ребёнка к детскому саду: постепенное знакомство, расставание, игра и самостоятельность. Не гарантируй срок адаптации.',school:'Составь для моего ребёнка короткую игровую подготовку к школе с учётом возраста. Без экзамена, баллов и обязательного чтения.',documents:'Помоги родителю в России разобраться в документах и выплатах. Не утверждай право, сумму или срок без проверенного действующего источника. Если данных нет, составь вопросы для СФР.'};
  ask(`${instructions[service]} Есть ${minutes} минут. Подробности: ${context.trim()||'Пока без дополнительных подробностей'}. Учитывай профиль ребёнка, сохранённые результаты и дневник. Не повторяй вопросы, ответы на которые уже известны.`);
 }
 async function generateWeek(){
  const generated=makeWeek(p,care,day),existing=new Set(care.tasks.map(t=>t.id));
  await update({...care,tasks:[...care.tasks,...generated.filter(t=>!existing.has(t.id))]},'План на пять дней сохранён. Пропускать можно.');setPanel('plan');
 }
 async function generateDay(){
  const generated=makeDayPlan(p,care,day),existing=new Set(care.tasks.map(t=>t.id));
  await update({...care,tasks:[...care.tasks,...generated.filter(t=>!existing.has(t.id))]},'План на сегодня составлен. Его можно менять.');
 }
 async function addIdea(item:CareTask){
  if(care.tasks.some(t=>t.id===item.id))return;
  await update({...care,tasks:[...care.tasks,item]},'Идея добавлена в план на сегодня.');
 }
 function visitText(a:Appointment){return ['Памятка к приёму',contextLabel(p),`Дата: ${a.date}`,`Повод: ${a.reason}`,`Мои вопросы:\n${a.questions||'Не записаны'}`,`Наблюдения родителя:\n${state.medicalCard.filter(e=>e.confirmation==='parent'||e.confirmation==='doctor').slice(0,12).map(e=>`${e.date}: ${e.text}`).join('\n')||'Нет подтверждённых записей'}`,`Последние заметки дневника:\n${care.diary.slice(-10).map(d=>`${d.date}: ${labels[d.kind]} — ${d.note}`).join('\n')}`,`После приёма, записано родителем дословно:\n${a.instructions||'Пока нет'}`,'Не является медицинским документом. Проверьте записи перед передачей врачу.'].join('\n\n');}
 const serviceInfo=serviceCatalog.find(s=>s[0]===service);
 return <div className="care-hub">
  {panel!=='overview'&&<Button variant="ghost" onClick={()=>setPanel('overview')}><ArrowLeft size={16}/>Мой день</Button>}
  {!p&&<section className="tile"><h2>Сначала познакомимся</h2><p>Для занятий нужен возраст ребёнка или срок беременности. Один профиль — один ребёнок.</p><Button onClick={onProfile}>Заполнить профиль</Button></section>}
  {panel==='overview'&&<>
   <section className="tile care-welcome"><div><span className="cap">Забота в действии</span><h2>{p?.role==='dad'?'Ваше время с ребёнком':'Сегодня достаточно одного шага'}</h2><p>План на день, игры и идеи развития подбираются по профилю ребёнка. Всё можно менять или пропускать.</p><div className="care-buttons"><Button variant="outline" onClick={()=>openService('calm')}><Heart size={16}/>Мне нужна поддержка</Button></div></div><Sparkles className="care-spark" size={60}/></section>
   <div className="care-quick">{[['plan','Мой план',CalendarDays],['diary','Дневник',ClipboardList],['safety','Развитие и дом',ShieldCheck],['visits','К врачу',Heart]].map(([id,title,Icon])=>{const I=Icon as typeof Heart;return <button key={id as string} onClick={()=>setPanel(id as string)}><I size={22}/>{title as string}</button>;})}</div>
   {!!reviews.length&&<section className="tile"><h3>Как получилось?</h3><p>Вы выбрали вернуться к этим действиям. Расскажите о результате, когда удобно.</p>{reviews.map(t=><button className="care-followup" key={t.id} onClick={()=>setPanel('plan')}>{t.title} <span>Поделиться результатом →</span></button>)}</section>}
   <section className="tile"><h3>План на сегодня</h3>{tasks.length?tasks.slice(0,3).map(t=><div className="care-task-preview" key={t.id}><span>{t.title}</span><Button variant="outline" onClick={()=>setPanel('plan')}>Открыть</Button></div>):<p>Составьте небольшой план из трёх подходящих идей. Если день загруженный, можно выбрать только одну.</p>}<div className="care-buttons"><Button disabled={!p||busy||care.tasks.length>96} onClick={()=>void generateDay()}>Составить план на день</Button><Button variant="outline" onClick={()=>setPanel('plan')}>Мои задачи</Button></div></section>
   <section><h3 className="mb-4">Игры и развитие</h3><div className="care-service-grid">{ideas.map(item=><article className="tile care-service" key={item.id}><strong>{item.title}</strong><span>{item.detail}</span><Button variant="outline" disabled={busy||care.tasks.length>=100||care.tasks.some(t=>t.id===item.id)} onClick={()=>void addIdea(item)}>{care.tasks.some(t=>t.id===item.id)?'В плане':'Добавить в план'}</Button></article>)}</div><div className="care-buttons mt-4"><Button variant="outline" disabled={!p||busy} onClick={()=>ask('Предложи ещё несколько безопасных игр и занятий для моего ребёнка на сегодня. Используй данные профиля молча, не повторяй возраст. Для каждой идеи дай короткие шаги и вариант упрощения.')}>Предложить ещё с AI</Button></div></section>
   <section className="tile"><h3>Ваша неделя — без сравнения с другими</h3><p>{summary.entries} записей в дневнике · {summary.completed} выполненных действий. Пропуски не уменьшают «оценку» — оценок здесь нет.</p><Button variant="outline" onClick={()=>setPanel('diary')}>Посмотреть наблюдения</Button></section>
  </>}
  {panel==='service'&&serviceInfo&&<section className="tile service-panel"><span className="cap">{serviceInfo[2]}</span><h2>{serviceInfo[1]}</h2><p>Ответ придёт в ваш текущий AI-диалог.</p>{service==='school'&&p?.stage==='child'&&age!==null&&age<48&&<p className="service-note">Сейчас предложим обычные игры по возрасту, а не школьные занятия.</p>}
   <form className="service-stack" onSubmit={e=>{e.preventDefault();serviceQuestion();}}><label className="form-field">Время<select value={minutes} onChange={e=>setMinutes(e.target.value)}>{['2','5','10','20'].map(m=><option key={m} value={m}>{m} минут</option>)}</select></label><label className="form-field">{serviceInfo[3]}<Textarea maxLength={900} value={context} onChange={e=>setContext(e.target.value)} placeholder={service==='play'?'Например: есть большая картонная коробка и книга. Ребёнок любит животных.':'Можно коротко, своими словами'}/></label><Button disabled={busy||(!p&&!['calm','dad','documents','now'].includes(service))}>Обсудить с помощником</Button></form>{service==='documents'&&<p className="muted">Для точных условий используйте раздел «Семьям с детьми» на <a href="https://sfr.gov.ru/grazhdanam/semyam_s_detmi/" target="_blank" rel="noreferrer">сайте СФР</a>. Суммы и право на выплату автоматически не рассчитываются. Проверяйте дату и свой регион.</p>}
  </section>}
  {panel==='plan'&&<section className="tile"><h2>Мой план и результаты</h2><p>План подстраивается под возраст. Занятия с отметкой «Было трудно» не повторяются в подборке следующие 14 дней. Это не диагностика развития.</p><div className="care-buttons"><Button disabled={busy||!p||care.tasks.length>95} onClick={()=>void generateWeek()}>Подобрать пять дней</Button><label className="care-check"><input type="checkbox" checked={care.followups} disabled={busy} onChange={e=>void update({...care,followups:e.target.checked})}/>Спрашивать о результате в кабинете</label></div><form className="care-inline" onSubmit={async e=>{e.preventDefault();if(await update({...care,tasks:[...care.tasks,{id:uid(),title:newTask.trim(),detail:'Моя личная задача',date:day,status:'planned',feedback:''}]}))setNewTask('');}}><Input aria-label="Новое действие" required maxLength={180} value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="Добавить своё действие"/><Button disabled={busy||!newTask.trim()||care.tasks.length>=100}><Plus size={18}/>Добавить</Button></form>
   {!care.tasks.length&&<p>Пока пусто. Можно создать план или сохранить действие из ответа AI кнопкой «В мой план».</p>}{[...care.tasks].sort((a,b)=>a.date.localeCompare(b.date)).map(t=><article key={t.id} className="care-task"><span className="cap">{t.date} · {t.status==='done'?'Готово':t.status==='skip'?'Пропущено':'Запланировано'}</span><h3>{t.title}</h3><p className="care-pre">{t.detail}</p><div className="care-buttons"><Button variant="outline" disabled={busy} onClick={()=>void update({...care,tasks:care.tasks.map(x=>x.id===t.id?{...x,status:x.status==='done'?'planned':'done'}:x)})}><Check size={16}/>{t.status==='done'?'Вернуть в план':'Готово'}</Button><Button variant="ghost" disabled={busy} onClick={()=>void update({...care,tasks:care.tasks.map(x=>x.id===t.id?{...x,status:'skip'}:x)})}>Пропустить</Button><Button variant="ghost" onClick={()=>calendarDownload(t)}>В календарь</Button><Button variant="ghost" disabled={busy} onClick={()=>ask(`Помоги адаптировать занятие для моего ребёнка: ${t.title}. ${t.detail.slice(0,600)}. Результат: ${t.result||'не пробовали'}. ${t.feedback||''}`)}>Адаптировать с AI</Button><Button variant="ghost" disabled={busy} onClick={()=>{if(confirm('Удалить действие и его результат?'))void update({...care,tasks:care.tasks.filter(x=>x.id!==t.id)});}}>Удалить</Button></div><label className="form-field">Вернуться к результату · необязательно<Input type="date" disabled={busy} value={t.reviewDate||''} onChange={e=>void update({...care,tasks:care.tasks.map(x=>x.id===t.id?{...x,reviewDate:e.target.value||undefined}:x)})}/></label><label className="form-field">Что получилось?<Textarea maxLength={400} value={feedback[t.id]??t.feedback} onChange={e=>setFeedback({...feedback,[t.id]:e.target.value})}/></label><div className="care-buttons">{[['helped','Помогло'],['neutral','Пока непонятно'],['hard','Было трудно']].map(([value,label])=><Button key={value} variant={t.result===value?'default':'outline'} disabled={busy} onClick={()=>void update({...care,tasks:care.tasks.map(x=>x.id===t.id?{...x,result:value as CareTask['result'],feedback:feedback[t.id]??t.feedback}:x)},'Результат сохранён и будет учтён помощником')}>{label}</Button>)}</div></article>)}
  </section>}
  {panel==='diary'&&<section className="tile"><h2>Дневник и наблюдения</h2><p>Записывайте только то, что хотите сохранить. Все записи доступны AI в контексте ваших вопросов. Не указывайте документы и чужие личные данные.</p><div className="service-note">За последние 7 дней: {summary.entries} записей; сон — {summary.sleepMinutes} минут в {summary.sleepRecords} записях; трудные дни родителя — {summary.difficultDays}. Это сумма введённых эпизодов, не весь сон и не оценка нормы.</div><form className="service-stack" onSubmit={async e=>{e.preventDefault();if(await update({...care,diary:[...care.diary,entry]}))setEntry({...entry,id:uid(),note:'',minutes:undefined});}}><div className="form-grid"><label className="form-field">Дата<Input type="date" required max={day} value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/></label><label className="form-field">Что записать<select value={entry.kind} onChange={e=>setEntry({...entry,kind:e.target.value as DiaryEntry['kind'],minutes:undefined,mood:''})}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>{entry.kind==='sleep'&&<label className="form-field">Длительность эпизода в минутах<Input type="number" min={0} max={1440} required value={entry.minutes??''} onChange={e=>setEntry({...entry,minutes:e.target.value===''?undefined:Number(e.target.value)})}/></label>}{entry.kind==='mood'&&<label className="form-field">Как прошёл день<select required value={entry.mood} onChange={e=>setEntry({...entry,mood:e.target.value as DiaryEntry['mood']})}><option value="">Выберите</option><option value="easy">Спокойно</option><option value="mixed">По-разному</option><option value="hard">Трудно</option></select></label>}<label className="form-field">Короткая заметка<Textarea maxLength={500} value={entry.note} onChange={e=>setEntry({...entry,note:e.target.value})}/></label><Button disabled={busy||care.diary.length>=200||(!entry.note.trim()&&entry.minutes===undefined&&!entry.mood)}>Сохранить запись</Button></form><Button className="my-4" variant="outline" disabled={busy||!care.diary.length} onClick={()=>ask('Посмотри мой дневник наблюдений и результаты занятий за неделю. Назови только видимые повторения, не причинно-следственные связи и не диагнозы. Укажи неполноту данных. Предложи один небольшой следующий шаг для нашей семьи.')}>Обсудить неделю с AI</Button><div className="service-stack">{[...care.diary].reverse().map(d=><div className="care-record" key={d.id}><strong>{d.date} · {labels[d.kind]}</strong><p>{d.minutes!==undefined?`${d.minutes} мин. `:''}{d.mood?{easy:'Спокойно',mixed:'По-разному',hard:'Трудно'}[d.mood]:''} {d.note}</p><Button variant="ghost" disabled={busy} onClick={()=>void update({...care,diary:care.diary.filter(x=>x.id!==d.id)})}>Удалить запись</Button></div>)}</div></section>}
  {panel==='safety'&&<section className="tile"><h2>Открытия ребёнка и безопасный дом</h2><p>Навык отмечает родитель, а не AI. Нет обязательных сроков и сравнения с другими детьми.</p><form className="service-stack" onSubmit={async e=>{e.preventDefault();if(await update({...care,achievements:[...care.achievements,achievement]},'Событие сохранено. Список безопасности обновлён.'))setAchievement({...achievement,id:uid(),note:''});}}><label className="form-field">Событие<select value={achievement.kind} onChange={e=>setAchievement({...achievement,kind:e.target.value as Achievement['kind']})}>{Object.entries(eventLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="form-field">Дата<Input required type="date" max={day} value={achievement.date} onChange={e=>setAchievement({...achievement,date:e.target.value})}/></label><label className="form-field">Заметка<Input maxLength={300} value={achievement.note} onChange={e=>setAchievement({...achievement,note:e.target.value})}/></label><Button disabled={busy||care.achievements.length>=50||p?.stage!=='child'||(achievement.kind==='custom'&&!achievement.note.trim())}>Сохранить событие</Button></form><h3 className="mt-6">Что проверить дома</h3><p className="muted">Базовый список, не полный аудит безопасности. Новые пункты появляются после отметок о движении ребёнка.</p>{safetyItems(care).map(([id,label])=><label className="care-check care-check-row" key={id}><input type="checkbox" checked={care.checked.includes(id)} disabled={busy} onChange={e=>void update({...care,checked:e.target.checked?[...care.checked,id]:care.checked.filter(x=>x!==id)})}/>{label}</label>)}<Button variant="outline" className="my-4" disabled={busy} onClick={()=>ask('Помоги проверить безопасность дома для моего ребёнка с учётом отмеченных навыков. Это не полный аудит. Назови основные риски и что уточнить, без гарантий безопасности.')}>Обсудить безопасность с AI</Button>{[...care.achievements].reverse().map(a=><div className="care-record" key={a.id}><strong>{a.date} · {eventLabels[a.kind]}</strong><p>{a.note}</p><Button disabled={busy} variant="ghost" onClick={()=>void update({...care,achievements:care.achievements.filter(x=>x.id!==a.id)})}>Удалить</Button></div>)}</section>}
  {panel==='visits'&&<section className="tile"><h2>До и после приёма</h2><p>Соберите вопросы и факты. Записи не заменяют назначения врача. Помощник не меняет дозы и не исправляет медицинские указания.</p><form className="service-stack" onSubmit={async e=>{e.preventDefault();if(await update({...care,appointments:[...care.appointments,appointment]}))setAppointment({id:uid(),date:day,reason:'',questions:'',instructions:''});}}><label className="form-field">Дата приёма<Input required type="date" value={appointment.date} onChange={e=>setAppointment({...appointment,date:e.target.value})}/></label><label className="form-field">Повод<Input required maxLength={300} value={appointment.reason} onChange={e=>setAppointment({...appointment,reason:e.target.value})}/></label><label className="form-field">Мои вопросы<Textarea maxLength={1500} value={appointment.questions} onChange={e=>setAppointment({...appointment,questions:e.target.value})}/></label><label className="form-field">Что сказал врач · можно записать после приёма<Textarea maxLength={2000} value={appointment.instructions} onChange={e=>setAppointment({...appointment,instructions:e.target.value})} placeholder="Перепишите дословно. Не загружайте фото документов."/></label><Button disabled={busy||care.appointments.length>=30||!appointment.reason.trim()}>Сохранить</Button></form>{[...care.appointments].reverse().map(a=><div className="care-record" key={a.id}><h3>{a.date} · {a.reason}</h3><p className="care-pre">{a.questions}</p><label className="form-field">После приёма: дословные указания<Textarea defaultValue={a.instructions} maxLength={2000} disabled={busy} onBlur={e=>{if(e.target.value!==a.instructions)void update({...care,appointments:care.appointments.map(x=>x.id===a.id?{...x,instructions:e.target.value}:x)});}}/></label><p className="muted text-sm">Сохраняется при выходе из поля.</p><div className="care-buttons"><Button variant="outline" onClick={()=>download('questions-for-doctor.txt',visitText(a))}>Скачать памятку к приёму</Button><Button disabled={busy} variant="outline" onClick={()=>ask(`Помоги сформулировать вопросы врачу для нашей семьи. Повод: ${a.reason}. Мои вопросы: ${a.questions.slice(0,800)}. Учитывай карту и дневник, только факты родителя, не ставь диагноз.`)}>Подготовиться с AI</Button><Button disabled={busy||!a.instructions.trim()||care.tasks.length>=100} variant="outline" onClick={()=>void update({...care,tasks:[...care.tasks,{id:uid(),title:'Уточнить и выполнить указания после приёма',detail:a.instructions,date:day,status:'planned',feedback:''}]},'Указания скопированы дословно. Проверьте дату и уточните непонятное у врача.')}>Дословно в мой план</Button><Button disabled={busy} variant="ghost" onClick={()=>{if(confirm('Удалить запись о приёме?'))void update({...care,appointments:care.appointments.filter(x=>x.id!==a.id)});}}>Удалить</Button></div></div>)}</section>}
 </div>;
}
