import { useState } from 'react';
import { Bib, Bottle, HeartCloud, Pacifier, Rattle, Socks } from '@/components/BabyIcons';
import { Fox } from '@/components/Critters';
const themes=[
  {title:'Беременность',art:Pacifier,bg:'bg-violet-soft',text:'Подготовка к приёму, вопросы о вашем этапе, организация первых дней дома.',example:'Какие вопросы записать перед приёмом?'},
  {title:'Кормление и уход',art:Bottle,bg:'bg-cream',text:'Как подготовить вопрос о кормлении и разобраться в ежедневном уходе. Без самостоятельных назначений.',example:'Что рассказать специалисту о кормлении?'},
  {title:'Сон малыша',art:Bib,bg:'bg-blue-soft',text:'Вопросы о сне в чате и возможность сохранить особенности режима в профиле.',example:'Что проверить перед сном?'},
  {title:'Игры и движение',art:Rattle,bg:'bg-sage-soft',text:'Идеи общения и совместных занятий. Упражнения и ограничения обсуждаются со специалистом.',example:'Как провести время вместе без сложных игрушек?'},
  {title:'Поддержка родителей',art:HeartCloud,bg:'bg-pink-soft',text:'Пауза при стрессе, просьба о помощи, разговор о нагрузке. Забота о маме и папе тоже важна.',example:'Мне трудно. Как попросить о поддержке?'},
  {title:'Возрастной советник',art:Socks,bg:'bg-violet-soft',text:'Только события по вашему этапу, с возможностью прочитать, отложить или скрыть карточку.',example:'Что нового на нашем этапе?'},
];
export default function Voices(){const [active,setActive]=useState(0);const selected=themes[active];return <section id="voices" className="scroll-mt-24 px-3 py-7 sm:px-5"><div className="mx-auto max-w-[1120px]"><span className="cap">Какая помощь здесь есть</span><h2 className="mb-5 font-heading text-[28px] leading-tight sm:text-[34px]">Маленькие вопросы — <span className="mark-hl">большая поддержка</span></h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{themes.map((t,i)=><button key={t.title} onClick={()=>setActive(i)} aria-pressed={active===i} className={`tile flex gap-4 text-left p-5 transition-transform motion-safe:hover:-translate-y-1 ${active===i?'ring-2 ring-primary':''}`}><span className={`grid h-14 w-14 shrink-0 place-items-center rounded-2xl ${t.bg}`}><t.art className="h-10 w-10"/></span><span><strong className="font-heading text-lg font-medium">{t.title}</strong><span className="mt-2 block text-base leading-relaxed text-muted-foreground">{t.text}</span></span></button>)}</div><div className="tile mt-4 flex flex-col gap-4 bg-inner p-5 sm:flex-row sm:items-center"><Fox className="h-14 w-14 shrink-0"/><div className="flex-1"><span className="cap">Например</span><p className="font-heading text-xl">«{selected.example}»</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Создайте личный аккаунт — и помощник ответит на ваш вопрос в чате.</p></div><a href="/account" className="rounded-full bg-gradient-to-r from-violet to-blue px-6 py-3 text-center font-medium text-white">Создать аккаунт</a></div></div></section>;}