"""Export the same monthly games and rules for browser/legacy fallbacks."""
import ast,importlib.util,json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
backend=root/'backend/parent-app'
spec=importlib.util.spec_from_file_location('export_catalog',backend/'daily_catalog.py')
catalog=importlib.util.module_from_spec(spec);spec.loader.exec_module(catalog)
items=[]
for month in range(catalog.MAX_MONTHS):
    for g in catalog.candidates(month):
        if g['minMonths']!=month:continue
        items.append(dict(id=g['id'],baseId=g['baseId'],min=g['minMonths'],max=g['maxMonths'],title=g['title'],detail=g['goal']+' '+' '.join(g['steps']),materials=g['materials'],area=g['area']))
(root/'ai-proxy/age-play-catalog.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
rules=next(n.value for n in ast.parse((backend/'content_policy.py').read_text(encoding='utf8')).body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='RULES' for t in n.targets))
(root/'ai-proxy/content-policy.js').write_text('// Generated by scripts/export-age-play.py.\nexport const CONTENT_RULES = '+json.dumps(ast.literal_eval(rules),ensure_ascii=False)+';\n',encoding='utf8')
print('Monthly fallback games:',len(items))
